name: GitHub Actions Demo
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: 'Create .env file'
        run: |
          touch .env
          echo CONNECTION_STRING="${{ secrets.MONGO_DB_CONNECTION_STRING }}" >> .env
      - name: 'check repo'
        run: ls -l ${{ github.workspace }}
      - run: npm install
      - run: npm test